### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by amery** [leonardorafael/material-dynamic-colors#1]
hi, I would like to be able to use `metailDynamicColors` server side but currently, the code is designed to export it via `window`.

I'm a noob on the frontend/nodejs world . Could you suggest how to refactor material-dynamic-colors.js so it can be used via `import` on vue3/nuxt3 composables?

**Comment by leonardorafael** [comment]
Hi @amery, we released a new version (0.1.2) with SSR support https://github.com/leonardorafael/material-dynamic-colors#npm
I tested on next.js, but I think this will work on nuxt.js too.

Can you confirm @amery?

**Comment by amery** [comment]
@leonardorafael sorry for disappearing. I can happily confirm it works on Nuxt 3 :)
