### ISSUE TITLE
Incorrect output generated by the ES5 version of the library

### ISSUE THREAD

**Issue by patelka2211** [leonardorafael/material-dynamic-colors#3]
I have encountered an issue with the ES5 version of the library after converting it from ES6. The purpose of the conversion was to ensure compatibility with a wide range of modern browsers. However, I have noticed unexpected output when using the converted code.

Here are the discrepancies between the expected output (ES6) and the actual output (ES5) for various input HEX colors:

**For input HEX color `#ff0000`**

-   The 'primary' property should be `#c10000` (ES6) but is `#c100` (ES5).
-   The 'onPrimaryContainer' property should be `#410000` (ES6) but is `#4100` (ES5).
-   The 'onTertiaryContainer' property should be `#261a00` (ES6) but is `#261a0` (ES5).
-   The 'onErrorContainer' property should be `#410001` (ES6) but is `#4101` (ES5).
-   The 'shadow' property should be `#000000` (ES6) but is `#000` (ES5).

**For input HEX color `#00ff00`**

-   The 'primary' property should be `#006f00` (ES6) but is `#06f0` (ES5).
-   The 'onPrimaryContainer' property should be `#002200` (ES6) but is `#0220` (ES5).
-   The 'onSecondaryContainer' property should be `#121f0e` (ES6) but is `#121fe` (ES5).
-   The 'onTertiaryContainer' property should be `#002022` (ES6) but is `#02022` (ES5).
-   The 'onErrorContainer' property should be `#410001` (ES6) but is `#4101` (ES5).
-   The 'inversePrimary' property should be `#00e600` (ES6) but is `#0e60` (ES5).
-   The 'shadow' property should be `#000000` (ES6) but is `#000` (ES5).

**For input HEX color `#0000ff`**

-   The 'onPrimaryContainer' property should be `#00006f` (ES6) but is `#006f` (ES5).
-   The 'onErrorContainer' property should be `#410001` (ES6) but is `#4101` (ES5).
-   The 'shadow' property should be `#000000` (ES6) but is `#000` (ES5).

Additional Information:

-   ES6 to ES5 conversion was done by TypeScript.
-   By observation its clear that ES5 code is making some mistake in number of zeros present in output HEX color.

**Comment by leonardorafael** [comment]
I will investigate that, thanks @patelka2211

**Comment by leonardorafael** [comment]
Can you test again in version 1.0.1? We changed to official lib of material design and build using vite.

![image](https://github.com/leonardorafael/material-dynamic-colors/assets/12979016/3321f2af-5ddf-4df6-9dd7-3e1d21647554)

**Comment by laurentpayot** [comment]
By the way @leonardorafael can you tell us how [`--inverse-on-primary`](https://github.com/beercss/beercss/blob/aa5931f37137d7e8031391085723be9fbd12a7dc/src/cdn/settings/light.css#L29) is generated? It is not in the exports of the [official Material Design theme builder](https://m3.material.io/theme-builder#/custom) :thinking:

**Comment by leonardorafael** [comment]
> By the way @leonardorafael can you tell us how [`--inverse-on-primary`](https://github.com/beercss/beercss/blob/aa5931f37137d7e8031391085723be9fbd12a7dc/src/cdn/settings/light.css#L29) is generated? It is not in the exports of the [official Material Design theme builder](https://m3.material.io/theme-builder#/custom) 🤔

Oh I see, this is not to be generated @laurentpayot. It can be removed. The latest version outputs:

```
await materialDynamicColors("#ffd700"); // from material-dynamic-colors lib

{
   "light":{
      "primary":"#705d00",
      "onPrimary":"#ffffff",
      "primaryContainer":"#ffe16d",
      "onPrimaryContainer":"#221b00",
      "secondary":"#675e40",
      "onSecondary":"#ffffff",
      "secondaryContainer":"#efe2bc",
      "onSecondaryContainer":"#211b04",
      "tertiary":"#44664e",
      "onTertiary":"#ffffff",
      "tertiaryContainer":"#c6eccd",
      "onTertiaryContainer":"#00210e",
      "error":"#ba1a1a",
      "onError":"#ffffff",
      "errorContainer":"#ffdad6",
      "onErrorContainer":"#410002",
      "background":"#fffbff",
      "onBackground":"#1d1b16",
      "surface":"#fffbff",
      "onSurface":"#1d1b16",
      "surfaceVariant":"#eae2cf",
      "onSurfaceVariant":"#4b4739",
      "outline":"#7c7767",
      "outlineVariant":"#cdc6b4",
      "shadow":"#000000",
      "scrim":"#000000",
      "inverseSurface":"#33302a",
      "inverseOnSurface":"#f6f0e7",
      "inversePrimary":"#e9c400"
   },
   "dark":{
      "primary":"#e9c400",
      "onPrimary":"#3a3000",
      "primaryContainer":"#544600",
      "onPrimaryContainer":"#ffe16d",
      "secondary":"#d2c6a1",
      "onSecondary":"#373016",
      "secondaryContainer":"#4e462a",
      "onSecondaryContainer":"#efe2bc",
      "tertiary":"#aad0b2",
      "onTertiary":"#153722",
      "tertiaryContainer":"#2d4e37",
      "onTertiaryContainer":"#c6eccd",
      "error":"#ffb4ab",
      "onError":"#690005",
      "errorContainer":"#93000a",
      "onErrorContainer":"#ffb4ab",
      "background":"#1d1b16",
      "onBackground":"#e8e2d9",
      "surface":"#1d1b16",
      "onSurface":"#e8e2d9",
      "surfaceVariant":"#4b4739",
      "onSurfaceVariant":"#cdc6b4",
      "outline":"#979080",
      "outlineVariant":"#4b4739",
      "shadow":"#000000",
      "scrim":"#000000",
      "inverseSurface":"#e8e2d9",
      "inverseOnSurface":"#33302a",
      "inversePrimary":"#705d00"
   }
}
```



```
await ui("theme", "#ffd700"); // from beercss lib

{
   "light":"--primary:#705d00;--on-primary:#ffffff;--primary-container:#ffe16d;--on-primary-container:#221b00;--secondary:#675e40;--on-secondary:#ffffff;--secondary-container:#efe2bc;--on-secondary-container:#211b04;--tertiary:#44664e;--on-tertiary:#ffffff;--tertiary-container:#c6eccd;--on-tertiary-container:#00210e;--error:#ba1a1a;--on-error:#ffffff;--error-container:#ffdad6;--on-error-container:#410002;--background:#fffbff;--on-background:#1d1b16;--surface:#fffbff;--on-surface:#1d1b16;--surface-variant:#eae2cf;--on-surface-variant:#4b4739;--outline:#7c7767;--outline-variant:#cdc6b4;--shadow:#000000;--scrim:#000000;--inverse-surface:#33302a;--inverse-on-surface:#f6f0e7;--inverse-primary:#e9c400;",
   "dark":"--primary:#e9c400;--on-primary:#3a3000;--primary-container:#544600;--on-primary-container:#ffe16d;--secondary:#d2c6a1;--on-secondary:#373016;--secondary-container:#4e462a;--on-secondary-container:#efe2bc;--tertiary:#aad0b2;--on-tertiary:#153722;--tertiary-container:#2d4e37;--on-tertiary-container:#c6eccd;--error:#ffb4ab;--on-error:#690005;--error-container:#93000a;--on-error-container:#ffb4ab;--background:#1d1b16;--on-background:#e8e2d9;--surface:#1d1b16;--on-surface:#e8e2d9;--surface-variant:#4b4739;--on-surface-variant:#cdc6b4;--outline:#979080;--outline-variant:#4b4739;--shadow:#000000;--scrim:#000000;--inverse-surface:#e8e2d9;--inverse-on-surface:#33302a;--inverse-primary:#705d00;"
}
```

**Comment by laurentpayot** [comment]
Thanks @leonardorafael. But if I remove `--inverse-on-primary`, won’t it impact the [`.inverse-primary`](https://github.com/beercss/beercss/blob/aa5931f37137d7e8031391085723be9fbd12a7dc/src/cdn/helpers/theme.css#L93) helper?

```css
.inverse-primary {
  background-color: var(--inverse-primary);
  color: var(--inverse-on-primary);
}
```

**Comment by patelka2211** [comment]
> Can you test again in version 1.0.1? We changed to official lib of material design and build using vite.
> 
> ![image](https://user-images.githubusercontent.com/12979016/251334670-3321f2af-5ddf-4df6-9dd7-3e1d21647554.png)

Yes @leonardorafael it works now.
