### ISSUE TITLE
materialDynamicColors Typescript export is typed incorrectly

### ISSUE THREAD

**Issue by rekkih** [leonardorafael/material-dynamic-colors#5]
Importing via `import materialDynamicColors from 'material-dynamic-colors'` works, but throws `TS2349: This expression is not callable.`

However, when importing `import {materialDynamicColors} from 'material-dynamic-colors'`, no error from Typescript, but obviously, isn't callable.

![image](https://github.com/leonardorafael/material-dynamic-colors/assets/17891896/c15046b7-5bd1-41a1-8558-b361d9f55d6f)

**Comment by leonardorafael** [comment]
Hi @rekkisomo , 

I can't reproduce this warning. I usually use the vanilla-ts template from Vite (https://vitejs.dev/guide/). I can't get this warning (TS2349) and any other warning. This is strange, can you give more details?

This is the online version of vanilla-ts template from Vite (importing material-dynamic-colors whitout warnings) https://stackblitz.com/edit/vitejs-vite-ulutck?file=src%2Fmain.ts (at least the IDE don't show nothing to me)

**Comment by rekkih** [comment]
Odd. FWIW, This is through NextJS with no changes to it's linting. I should've probably elaborated: importing isn't the thing throwing the warning, its using it as a function that does. Forcing ts-ignore resolves it which is what we're doing for now 😅

Re-attached with more context, as I noticed the screenshot above cut it out (probably due to sharex):
![image](https://github.com/leonardorafael/material-dynamic-colors/assets/17891896/584f073d-a277-45c2-971a-1d23d434e668)

Honestly, I don't know what else to provide. This is probably just limited to NextJS or IntelliJ. Building the code works completely fine, though!

**Comment by arg274** [comment]
I was able to repro this with a project scaffolded using `create-t3-app` OOTB.

**Comment by belyas** [comment]
I can confirm that this is happening for us with Nextjs app, I've just upgraded to the latest version and TS is complaining:

```ts
This expression is not callable.
  Type 'typeof import("~/repositories/projectname/node_modules/material-dynamic-colors/index")' has no call signatures.ts(2349)
```
When I import it as named import, the typing is working fine, but of course it's not a named export which will break the UI

FYI @leonardorafael 

Default import:
<img width="732" alt="Screenshot 2024-01-08 at 13 17 52" src="https://github.com/leonardorafael/material-dynamic-colors/assets/4919883/3c2ad49c-265a-4cf9-96de-e3733fa5e672">

Named import:
<img width="903" alt="Screenshot 2024-01-08 at 13 18 05" src="https://github.com/leonardorafael/material-dynamic-colors/assets/4919883/0d8476c8-bd4b-44aa-9405-73844e7bb73f">

I believe if you do something like this, it'd fix it:
```ts
export { default } from './material-dynamic-colors';
export * from './material-dynamic-colors';

// and inside "./material-dynamic-colors"
//... -> all the necessary types/interfaces
export default function materialDynamicColors(from: string | File | Blob | Event | HTMLImageElement): Promise<IMaterialDynamicColorsTheme>;
```

**Comment by Rohit3523** [comment]
Facing the same issue while importing this library in my react native app

@leonardorafael

**Comment by leonardorafael** [comment]
Hi, sorry for the delay, I released another version with some changes commented by @belyas on *.d.ts files and export.
I believe this should work.

Thanks for that @belyas

**Comment by belyas** [comment]
> Hi, sorry for the delay, I released another version with some changes commented by @belyas on *.d.ts files and export. I believe this should work.
> 
> Thanks for that @belyas

Thanks @leonardorafael looks good
